export const LOGIN = "LOGIN";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_COURSES = "GET_COURSES";
export const GET_STUDENT_COURSES = "GET_STUDENT_COURSES";
export const GET_TEACHER_COURSES = "GET_TEACHER_COURSES";
export const GET_GRADES = "GET_GRADES";
export const GET_STUDENT_GRADES = "GET_STUDENT_GRADES";
export const PUT_USER = "PUT_USER";
export const PUT_DOMAIN = "PUT_DOMAIN";
export const PUT_HOME = "PUT_HOME";
export const DELETE_ALL = "DELETE_ALL";
export const RELOAD_USER="RELOAD_USER"
export const LOG_OUT="LOG_OUT"