export const LOGIN="LOGIN"
export const GET_COURSES="GET_COURSES"
export const PUT_USER="PUT_USER"
export const GET_ALL_USERS="GET_ALL_USERS"
export const GET_GRADES="GET_GRADES"
export const PUT_DOMAIN="PUT_DOMAIN"